### ISSUE TITLE
Frontpage info blocks

### ISSUE THREAD

**Issue by mogmachine** [TaoStats/bittensor-explorer-ui#32]
I would like frontpage blocks like the examples below but in our style, with the inform below (this is a brainstorm from me, please feel free to contribute other information you think might be useful).

This is the give the explorer a real authority weight upon first landing.

- [x] TaoStats/bittensor-dictionary#21
- [x] TaoStats/bittensor-dictionary#22
- [x] TaoStats/bittensor-indexer#10
- [x] TaoStats/bittensor-indexer#11

- [x] TaoStats/bittensor-explorer-ui#37
- [x] TaoStats/bittensor-explorer-ui#38
- [x] TaoStats/bittensor-explorer-ui#35
- [x] TaoStats/bittensor-explorer-ui#36

Token Supply

Ideally this would be a single donut chart with 21m being thefull circle, then circulating supply taking up 23% and then staked supply taking up 88% of that 23%. The box would need to have those values clear on display (value AND %)

- Max Supply (21m)
- Circulating Supply (4.9m + % - taken from chain)
- Staked Supply (4.36m + % of circulating taken from chain)

![Image](https://user-images.githubusercontent.com/3446536/257039118-360fdc1c-c977-4281-81af-e1517e0a409c.JPG)
![Image](https://user-images.githubusercontent.com/3446536/257039117-cbcdc66b-0df5-4bed-978a-55e9e6f6258a.JPG)
![Image](https://user-images.githubusercontent.com/3446536/257039119-b9e49cec-c006-49a2-82e3-3ae281a2d219.JPG)

**Comment by TopETH** [comment]
WIP
![image](https://github.com/TaoStats/bittensor-explorer-ui/assets/79193919/992790d4-9c77-47e9-ad87-499a6ce72f66)

**Comment by TopETH** [comment]
@mogmachine 
![image](https://github.com/TaoStats/bittensor-explorer-ui/assets/79193919/5cb23d0f-f799-4b1a-8002-dd8224a31d7e)
